/* ===== EXPÉRIENCES, ITINÉRAIRES, LIEUX CACHÉS, INFOS PRATIQUES — Le Guide Cambodge ===== */
const EXPERIENCES = [
{id:"temples",name:"Temples & histoire",kh:"ប្រាសាទ",d:["siem-reap","preah-vihear","kampong-thom","banteay-meanchey","takeo","kampong-cham","phnom-penh"],blurb:"Angkor n'est que le début. Koh Ker, Sambor Prei Kuk, Banteay Chhmar et Preah Vihear vous emmènent plus loin dans 1 400 ans de constructions khmères."},
{id:"beaches",name:"Plages & îles",kh:"ឆ្នេរ",d:["sihanoukville","kep","koh-kong","kampot"],blurb:"La bioluminescence de Koh Rong, les baies de Koh Rong Sanloem, les hamacs de Koh Tonsay et les sables déserts de Koh Kong Krao."},
{id:"nature",name:"Nature & parcs nationaux",kh:"ធម្មជាតិ",d:["koh-kong","mondulkiri","ratanakiri","kampong-speu","stung-treng","kampot"],blurb:"Virachey, les Cardamomes, Keo Seima, Bokor, Kirirom, Ream : le Cambodge compte plus de forêts protégées que la plupart des gens l'imaginent."},
{id:"jungle",name:"Jungle & trekking",kh:"ព្រៃ",d:["koh-kong","ratanakiri","mondulkiri","kampong-speu"],blurb:"Treks de plusieurs jours depuis Chi Phat, expéditions avec les rangers du Virachey, sentiers des gibbons à Keo Seima et ascension du Phnom Aural."},
{id:"cycling",name:"Vélo",kh:"កង់",d:["battambang","kratie","kampong-cham","takeo","kandal","siem-reap","kampong-chhnang"],blurb:"Campagne de rizières plates, îles du Mékong sans voitures et petites routes de temples : le Cambodge est l'un des meilleurs pays d'Asie pour le vélo."},
{id:"motorbike",name:"Voyages à moto",kh:"ម៉ូតូ",d:["mondulkiri","ratanakiri","kampot","preah-vihear","pursat","pailin","oddar-meanchey"],blurb:"Les pistes de terre rouge du nord-est, la route de montagne des Cardamomes jusqu'à Osoam, la boucle des karsts de Kampot à Kep, les boucles de temples du nord."},
{id:"mekong",name:"Le Mékong",kh:"ទន្លេមេគង្គ",d:["kratie","stung-treng","kampong-cham","phnom-penh"],blurb:"Les dauphins de Kampi et d'Anlong Cheuteal, la forêt inondée de Stung Treng, les ponts de bambou, les séjours chez l'habitant sur les îles."},
{id:"wildlife",name:"Faune sauvage",kh:"សត្វព្រៃ",d:["mondulkiri","ratanakiri","preah-vihear","stung-treng","banteay-meanchey","koh-kong"],blurb:"Sanctuaires d'éléphants éthiques, gibbons, doucs, ibis géant, grues antigones, dauphins d'Irrawaddy, calaos."},
{id:"waterfalls",name:"Cascades",kh:"ទឹកធ្លាក់",d:["mondulkiri","ratanakiri","koh-kong","kampot","kampong-speu","stung-treng"],blurb:"Bou Sra, Ka Chanh, Tatai, Popokvil, Chambok et la Sopheakmit, large de 8 km, à la frontière du Laos."},
{id:"food",name:"Gastronomie",kh:"ម្ហូប",d:["phnom-penh","kampot","kep","battambang","siem-reap"],blurb:"Le crabe au poivre de Kampot, l'amok, le num banh chok, le nem de Battambang, le café du Mondulkiri et les meilleures soupes de nouilles d'Asie du Sud-Est."},
{id:"nightlife",name:"Vie nocturne",kh:"យប់",d:["phnom-penh","siem-reap","sihanoukville"],blurb:"Cocktails à Bassac Lane, bars sur les toits au-dessus du Mékong, Pub Street quand on en a envie et soirées sur la plage à Koh Rong."},
{id:"markets",name:"Marchés & artisanat",kh:"ផ្សារ",d:["phnom-penh","kampong-chhnang","kandal","battambang","siem-reap","pailin"],blurb:"Le dôme Art déco de Psar Thmei, les tisserands de soie de Koh Dach, les potiers d'Andong Russey, les négociants de gemmes de Pailin."},
{id:"wellness",name:"Bien-être & retraites",kh:"សុខភាព",d:["kep","kampot","siem-reap","sihanoukville"],blurb:"Yoga à Kep, retraites au bord de la rivière à Kampot, méditation à Oudong, hôtels-spas autour de Siem Reap."},
{id:"adventure",name:"Aventure",kh:"ផ្សងព្រេង",d:["koh-kong","mondulkiri","ratanakiri","siem-reap","kampot"],blurb:"Tyroliennes, escalade sur les karsts de Kampot, kayak dans les mangroves, camps dans la jungle et expéditions au Virachey."},
{id:"family",name:"En famille",kh:"គ្រួសារ",d:["siem-reap","kep","sihanoukville","kandal","kampong-speu","phnom-penh"],blurb:"Le cirque Phare, les plages des îles, le centre de sauvetage de la faune, le camping au Kirirom et des journées de temples tout en douceur."},
{id:"romantic",name:"Romantique",kh:"ស្នេហា",d:["kampot","kep","sihanoukville","siem-reap"],blurb:"Croisières aux lucioles, baies d'îles privées, camps de tentes dans la jungle et coucher de soleil sur les douves d'Angkor."},
{id:"luxury",name:"Luxe",kh:"ប្រណីត",d:["siem-reap","phnom-penh","sihanoukville","koh-kong"],blurb:"Camps de tentes près de Banteay Srei, resorts sur îles privées, croisières fluviales et survol d'Angkor en hélicoptère."},
{id:"backpacker",name:"Routard",kh:"ថវិកាតិច",d:["siem-reap","kampot","sihanoukville","battambang","kratie","phnom-penh"],blurb:"Le grand classique coûte encore 25 USD par jour si vous le voulez, et les bus vont partout."},
{id:"community",name:"Tourisme communautaire",kh:"សហគមន៍",d:["koh-kong","banteay-meanchey","kratie","pursat","kampong-speu","ratanakiri","preah-vihear","stung-treng"],blurb:"Chi Phat, Banteay Chhmar, Chambok, Osoam, Tmatboey, Koh Pdao : des villages qui gèrent eux-mêmes leur tourisme et en gardent les revenus."},
{id:"rural",name:"Cambodge rural",kh:"ជនបទ",d:["takeo","kampong-chhnang","pursat","prey-veng","tbong-khmum","svay-rieng","kampong-thom"],blurb:"Là où vivent 80 % des Cambodgiens : riz, sucre de palme, pagodes, chars à bœufs et hospitalité extraordinaire."},
{id:"photo",name:"Photographie",kh:"ថតរូប",d:["siem-reap","battambang","kampong-chhnang","mondulkiri","stung-treng","kep"],blurb:"L'envol des chauves-souris au Phnom Sampov, les villages flottants à l'aube, la brume de la Sea Forest, la forêt inondée, les ruines modernistes de Kep."}
];
const TRIPS = [
{id:"first-time",name:"Première fois au Cambodge",days:10,route:["phnom-penh","kampot","kep","siem-reap"],pitch:"La boucle essentielle, avec deux provinces que la plupart des primo-visiteurs oublient : le pays du poivre et la côte.",plan:["J1-2 Phnom Penh : Palais, musées, front de fleuve, gastronomie","J3-5 Kampot et Kep : Bokor, fermes de poivre, marché aux crabes, Koh Tonsay","J6 Avion ou bus vers Siem Reap","J7-9 Angkor en trois temps : grand circuit, Banteay Srei et Beng Mealea, villages du Tonlé Sap","J10 Phnom Kulen et départ"]},
{id:"hidden",name:"Cambodge caché",days:14,route:["phnom-penh","kampong-thom","preah-vihear","stung-treng","ratanakiri","mondulkiri","kratie"],pitch:"Sans Angkor du tout. Capitales préangkoriennes, temples sur falaise, forêts inondées, lacs de cratère et éléphants.",plan:["J1 Phnom Penh","J2 Sambor Prei Kuk","J3-4 Koh Ker, Prasat Bakan, Preah Vihear","J5-6 Forêt inondée de Stung Treng","J7-9 Ratanakiri : Yeak Laom, trek au Virachey","J10-12 Mondulkiri : éléphants, Bou Sra, villages bunong","J13-14 Dauphins de Kratie, retour à Phnom Penh"]},
{id:"motorbike",name:"Le Cambodge à moto",days:14,route:["phnom-penh","kampong-cham","kratie","mondulkiri","ratanakiri","stung-treng","preah-vihear","siem-reap"],pitch:"1 600 km de routes du Mékong, de terre rouge, de boucles des hauts plateaux et de pistes de temples. Louez une 250 cc à Phnom Penh.",plan:["J1-2 Phnom Penh, Kampong Cham et Kratie le long du Mékong","J3-5 Boucle du Mondulkiri : Bou Sra, Dak Dam, Sea Forest","J6 Piste de Koh Nhek vers Banlung","J7-8 Cascades du Ratanakiri et boucle de Ta Veng","J9 Stung Treng","J10-11 Temple de Preah Vihear, Koh Ker, Beng Mealea","J12-14 Siem Reap et Phnom Kulen"]},
{id:"beaches",name:"Plages & îles",days:7,route:["sihanoukville","kep","kampot"],pitch:"Trois îles, un marché aux crabes, une rivière.",plan:["J1-3 Koh Rong Sanloem : Saracen Bay, M'Pai Bay, plongée","J4 Long Beach à Koh Rong et nage de nuit dans le plancton","J5 Kep et Koh Tonsay","J6-7 Rivière de Kampot, poivre, Bokor"]},
{id:"temples",name:"Temples & culture",days:10,route:["phnom-penh","takeo","kampong-thom","siem-reap","preah-vihear","banteay-meanchey"],pitch:"Dans l'ordre chronologique : Funan, Chenla, Angkor, temples-frontières de Jayavarman VII.",plan:["J1 Musée national de Phnom Penh","J2 Angkor Borei et Phnom Da (Funan)","J3 Sambor Prei Kuk (Chenla)","J4-6 Angkor","J7 Koh Ker et Beng Mealea","J8 Preah Vihear","J9-10 Chez l'habitant à Banteay Chhmar et dîner au temple"]},
{id:"nature",name:"Nature & aventure",days:12,route:["koh-kong","kampong-speu","mondulkiri","ratanakiri"],pitch:"Les deux bords sauvages du pays : les Cardamomes et les hauts plateaux de l'est.",plan:["J1-4 Trek de Chi Phat et rivière Tatai","J5 Kirirom ou Phnom Aural","J6-8 Éléphants du Mondulkiri et gibbons de Keo Seima","J9-12 Expédition au Virachey"]},
{id:"luxury",name:"Cambodge de luxe",days:8,route:["siem-reap","phnom-penh","sihanoukville"],pitch:"Camps de tentes, croisière fluviale, île privée.",plan:["J1-3 Camp de tentes à Siem Reap, guide privé à Angkor, vol en hélicoptère","J4-5 Croisière sur le Mékong jusqu'à Phnom Penh, hôtel design","J6-8 Resort sur île privée au large de Koh Rong"]},
{id:"family",name:"Cambodge en famille",days:10,route:["siem-reap","phnom-penh","kep","sihanoukville"],pitch:"Trajets courts, piscines, animaux, plages et un cirque.",plan:["J1-3 Siem Reap : Angkor en tuk tuk, cirque Phare, bateau sur le Tonlé Sap","J4-5 Phnom Penh et centre de faune de Phnom Tamao","J6-7 Promenade dans le parc de Kep et Koh Tonsay","J8-10 Plages de Koh Rong Sanloem"]},
{id:"budget",name:"Cambodge petit budget",days:14,route:["siem-reap","battambang","phnom-penh","kampot","sihanoukville"],pitch:"25 à 35 USD par jour, bus de nuit, auberges, street food, et les mêmes temples que tout le monde.",plan:["J1-4 Siem Reap à vélo","J5-6 Train de bambou et chauves-souris de Battambang","J7-8 Phnom Penh","J9-11 Kampot en scooter","J12-14 Auberges de Koh Rong"]},
{id:"mekong",name:"Le Mékong à petit rythme",days:7,route:["phnom-penh","kampong-cham","kratie","stung-treng"],pitch:"Remontez le fleuve vers le Laos.",plan:["J1 Croisière au coucher du soleil à Phnom Penh","J2 Pont de bambou de Kampong Cham, Wat Hanchey","J3-4 Kratie, Koh Trong, dauphins","J5-6 Forêt inondée de Stung Treng","J7 Passage vers les 4 000 Îles"]},
{id:"food",name:"Voyage gourmand",days:7,route:["phnom-penh","battambang","kampot","kep"],pitch:"Marchés à l'aube, poivre à midi, crabe au crépuscule.",plan:["J1-2 Street food et cours de cuisine à Phnom Penh","J3-4 Galettes de riz, nem et cuisines de campagne à Battambang","J5-6 Fermes de poivre et restaurants au bord de la rivière à Kampot","J7 Marché aux crabes de Kep"]},
{id:"community",name:"Séjours communautaires",days:12,route:["banteay-meanchey","preah-vihear","kratie","koh-kong"],pitch:"Dormez dans des villages qui gèrent leur tourisme.",plan:["J1-2 Banteay Chhmar","J3-4 Oiseaux de Tmatboey","J5-6 Koh Pdao / Koh Trong","J7-12 Trek de Chi Phat et Tatai"]},
{id:"romantic",name:"Escapade romantique",days:6,route:["kampot","kep","sihanoukville"],pitch:"Rivière, karst, crabe, île.",plan:["J1-2 Lodge au bord de la rivière à Kampot et croisière aux lucioles","J3 Coucher de soleil à Kep et villa","J4-6 Baie privée à Koh Rong Sanloem"]},
{id:"cycling",name:"Cambodge à vélo",days:10,route:["siem-reap","battambang","kampong-chhnang","phnom-penh","kratie"],pitch:"Plat, accueillant, et toutes les routes finissent devant une pagode.",plan:["J1-3 Petites routes d'Angkor","J4-5 Campagne de Battambang","J6 Villages de potiers de Kampong Chhnang","J7-8 Koh Dach et Phnom Penh","J9-10 Koh Trong et Mekong Discovery Trail"]},
{id:"rural",name:"Week-end rural",days:3,route:["takeo","kampong-chhnang","kandal"],pitch:"Trois provinces, zéro touriste, toutes à moins de 2 h de la capitale.",plan:["J1 Bateau de Takeo à Phnom Da","J2 Poterie et village flottant de Kampong Chhnang","J3 Oudong et Koh Dach"]},
{id:"backpacker",name:"Boucle routard",days:21,route:["siem-reap","battambang","phnom-penh","kampot","kep","sihanoukville","koh-kong"],pitch:"La grande boucle du sud-ouest, avec le temps de ralentir.",plan:["Semaine 1 Siem Reap et Battambang","Semaine 2 Phnom Penh, Kampot, Kep","Semaine 3 Îles et Chi Phat"]},
{id:"trekking",name:"Trekking",days:9,route:["koh-kong","kampong-speu","ratanakiri"],pitch:"Cardamomes, Aural, Virachey.",plan:["J1-3 Chi Phat","J4-5 Phnom Aural","J6-9 Virachey"]},
{id:"adventure",name:"Aventure",days:9,route:["kampot","koh-kong","mondulkiri"],pitch:"Grimper, pagayer, tyrolienne, trek.",plan:["J1-2 Escalade et kayak à Kampot","J3-5 Tatai et Chi Phat","J6-9 Tyrolienne du Mondulkiri et trek des gibbons"]},
{id:"wildlife",name:"Faune sauvage",days:10,route:["banteay-meanchey","preah-vihear","kratie","mondulkiri"],pitch:"Grues, ibis, dauphins, éléphants, gibbons.",plan:["J1-2 Grues d'Ang Trapeang Thmor","J3-4 Ibis de Tmatboey","J5-6 Dauphins de Kampi","J7-10 Éléphants du Mondulkiri et Keo Seima"]},
{id:"photo",name:"Photographie",days:8,route:["siem-reap","battambang","kampong-chhnang","mondulkiri"],pitch:"Uniquement aux heures dorées.",plan:["J1-3 Angkor et villages du Tonlé Sap","J4-5 Chauves-souris et rizières de Battambang","J6 Aube flottante à Chhnok Tru","J7-8 Brume de la Sea Forest"]},
{id:"markets",name:"Artisanat & marchés",days:5,route:["phnom-penh","kandal","kampong-chhnang","battambang"],pitch:"Soie, argile, galettes de riz, art.",plan:["J1 Psar Thmei et Marché russe","J2 Soie de Koh Dach","J3 Poterie d'Andong Russey","J4-5 Ateliers de Battambang"]},
{id:"wellness",name:"Bien-être",days:6,route:["kep","kampot","siem-reap"],pitch:"Yoga, rivière, spa.",plan:["J1-2 Retraite yoga à Kep","J3-4 Lodge au bord de la rivière à Kampot","J5-6 Resort-spa à Siem Reap"]},
{id:"nightlife",name:"Nuits en ville",days:4,route:["phnom-penh","siem-reap"],pitch:"Toits, cocktails, musique live.",plan:["J1-2 Bassac Lane et rooftops du front de fleuve","J3-4 Bars de Kandal Village à Siem Reap et Phare"]},
{id:"waterfalls",name:"Chasse aux cascades",days:8,route:["kampot","mondulkiri","ratanakiri"],pitch:"Du Bokor à Bou Sra et Ka Chanh.",plan:["J1-2 Popokvil et Teuk Chhou","J3-5 Bou Sra, Dak Dam, Romanear","J6-8 Ka Chanh, Cha Ong, Katieng"]},
{id:"jungle",name:"Immersion en jungle",days:8,route:["koh-kong","ratanakiri"],pitch:"Deux forêts tropicales, deux équipes de rangers.",plan:["J1-4 Cardamomes depuis Chi Phat","J5-8 Virachey"]},
{id:"nature-short",name:"La nature en une semaine",days:7,route:["kampong-speu","kampot","koh-kong"],pitch:"Boucle verte du sud-ouest.",plan:["J1 Kirirom","J2-3 Bokor et rivière de Kampot","J4-7 Tatai et Chi Phat"]}
];
const HIDDEN = [
{t:"La vallée d'Areng",p:"koh-kong",s:"Une vallée des Cardamomes sauvée d'un barrage par ses habitants chong. Bassins aux poissons-dragons, forêt tropicale, chambres chez l'habitant."},
{t:"Prasat Bakan (Preah Khan de Kampong Svay)",p:"preah-vihear",s:"La plus vaste enceinte de l'empire d'Angkor, 5 km de côté, et vous y serez sans doute seul."},
{t:"La cascade de Sopheakmit",p:"stung-treng",s:"La plus large cascade du Cambodge, à la frontière du Laos, rugissante en septembre."},
{t:"Koh Kong Krao",p:"koh-kong",s:"La plus grande île du Cambodge : 100 km² de jungle et sept plages, sans aucun resort."},
{t:"Les enceintes circulaires de Memot",p:"tbong-khmum",s:"Des habitats vieux de 4 000 ans, uniques en Asie du Sud-Est, au cœur des plantations d'hévéas."},
{t:"Chhnok Tru à l'aube",p:"kampong-chhnang",s:"Une ville flottante de 10 000 habitants avec écoles, boutiques et pagodes, vue depuis une barque à rames."},
{t:"Tmatboey",p:"preah-vihear",s:"Le meilleur endroit au monde pour voir l'ibis géant, oiseau national du Cambodge, depuis un lodge de village."},
{t:"La Sea Forest, Mondulkiri",p:"mondulkiri",s:"Des collines vertes ondulées comme des vagues, enveloppées de brume avant 7 h du matin."},
{t:"Wat Maha Leap",p:"tbong-khmum",s:"Une pagode entièrement en bois du XIXe siècle aux colonnes dorées, l'une des dernières de son genre."},
{t:"Osoam",p:"pursat",s:"Un village de montagne des Cardamomes accessible par une piste, avec un lac, des cascades et un centre communautaire."}
];
/* link = page détaillée déjà existante sur le site */
const INFO = [
{id:"visa",t:"Visa",kh:"ទិដ្ឋាការ",link:["Le guide complet du visa","visa-cambodge/"],b:"La plupart des nationalités obtiennent un visa touristique de 30 jours : e-visa en ligne (evisa.gov.kh, 36 USD dont 6 USD de frais, délai de 3 jours ouvrables) ou visa à l'arrivée aux aéroports de Phnom Penh et de Siem Reap (35 USD en espèces, prévoir une photo d'identité). Les passeports de l'ASEAN sont exemptés. Le dépassement de séjour coûte 10 USD par jour. Les prolongations se font par l'intermédiaire d'agences à Phnom Penh."},
{id:"money",t:"Monnaie & paiements",kh:"លុយ",link:["Budget et argent","budget-voyage-cambodge/"],b:"Deux monnaies circulent en parallèle : le dollar américain pour tout ce qui dépasse environ 5 USD, le riel cambodgien (KHR, environ 4 100 pour un dollar) pour la petite monnaie. Les billets de dollars déchirés ou anciens sont refusés. Des distributeurs partout en ville (frais de 4 à 6 USD). Cartes acceptées dans les hôtels et les restaurants des villes. Les Cambodgiens paient avec le système QR Bakong / KHQR : certaines applications permettent désormais aux touristes de l'utiliser."},
{id:"sim",t:"Cartes SIM & internet",kh:"ស៊ីម",link:["Le guide pratique","guide-pratique-cambodge/"],b:"Achetez une SIM à l'aéroport ou dans n'importe quelle boutique avec votre passeport : Cellcard, Smart ou Metfone, environ 5 USD pour 20 Go ou plus. La couverture est bonne sur tout le réseau routier national, irrégulière dans les Cardamomes et au Virachey. Les eSIM fonctionnent mais coûtent plus cher. Le WiFi est dans tous les cafés."},
{id:"transport",t:"Se déplacer",kh:"ធ្វើដំណើរ",link:["Bus, bateaux, trains","transports/"],b:"Bus et minivans relient toutes les capitales de province (Giant Ibis, Virak Buntham, Larryta). Un taxi privé coûte 60 à 120 USD par jour. L'autoroute Phnom Penh-Sihanoukville prend 2 h. Des trains circulent de Phnom Penh vers Kampot / Sihanoukville et Poipet, avec des horaires limités. En ville : tuk tuk PassApp et Grab. Location de moto de 6 à 15 USD par jour (le permis est légalement obligatoire ; des contrôles de police ont lieu)."},
{id:"airports",t:"Aéroports",kh:"អាកាសយានដ្ឋាន",link:["Comparer les vols","vols/"],b:"Techo International (Phnom Penh, ouvert en 2025), Siem Reap-Angkor International (SAI, 2023, à 45 min de la ville) et Sihanoukville (KOS). Vols directs depuis Bangkok, Singapour, Kuala Lumpur, Hô Chi Minh-Ville, Hanoï, Séoul, Shanghai, Taipei et d'autres. Vols intérieurs : Phnom Penh-Siem Reap en 45 min."},
{id:"weather",t:"Climat & meilleures saisons",kh:"អាកាសធាតុ",link:["Quand partir au Cambodge","meilleure-periode-cambodge/"],b:"Sec et frais : de novembre à février (haute saison). Chaud : de mars à mai (35 à 40 °C, idéal pour la côte). Pluvieux : de juin à octobre, avec de courtes averses l'après-midi, des paysages verts, des cascades pleines, des hautes eaux pour les trajets en bateau et bien moins de visiteurs. Les îles sont plus calmes en juillet et août. Les hauts plateaux (Mondulkiri, Ratanakiri) sont plus frais toute l'année."},
{id:"safety",t:"Sécurité",kh:"សុវត្ថិភាព",link:["Le guide pratique","guide-pratique-cambodge/"],b:"Le Cambodge est sûr pour les voyageurs. Principaux risques : les vols à l'arraché depuis les tuk tuks à Phnom Penh (gardez votre téléphone en main), les accidents de la route (portez un casque) et les zones non balisées avec des mines dans les régions frontalières isolées (restez sur les sentiers près de Pailin, Preah Vihear et de la frontière thaïlandaise). Numéros d'urgence : police 117, ambulance 119, pompiers 118. Police touristique 012 942 484."},
{id:"customs",t:"Coutumes locales",kh:"ទំនៀមទម្លាប់",link:["Le guide pratique","guide-pratique-cambodge/"],b:"Saluez avec le sampeah (paumes jointes). Couvrez épaules et genoux dans les temples ; retirez chaussures et chapeau. Ne touchez jamais la tête de quelqu'un et ne pointez pas les pieds vers les gens ou les images du Bouddha. Les moines ne touchent pas les femmes. La colère fait perdre la face à tous : restez calme et souriez. Le pourboire n'est pas attendu mais 1 à 2 USD sont appréciés. Demandez avant de photographier des personnes, surtout dans les villages de minorités ethniques."},
{id:"khmer",t:"Bases de khmer",kh:"ភាសាខ្មែរ",link:["Le lexique khmer","lexique-khmer/"],b:"Bonjour : Sua s'dei (សួស្តី). Merci : Or kun (អរគុណ). Oui : baat (hommes) / jaa (femmes). Non : ot teh. Combien ça coûte : t'lai pon maan ? Délicieux : ch'ngain. Sans sucre : ot dak skor. Eau : teuk. Toilettes : bong kun. Chiffres : muoy, pii, bei, buon, pram (1 à 5). L'écriture khmère est un abugida de 33 consonnes ; l'anglais est très répandu dans les zones touristiques, le français chez les personnes âgées."},
{id:"health",t:"Santé",kh:"សុខភាព",link:["Le guide pratique","guide-pratique-cambodge/"],b:"De bons hôpitaux privés à Phnom Penh (Royal Phnom Penh, Sunrise Japan) et à Siem Reap (Royal Angkor International). Les pharmacies (U-Care, Pharmacie de la Gare) vendent la plupart des médicaments sans ordonnance. Voyagez avec une assurance incluant le rapatriement. Vaccins : hépatites A et B, typhoïde, tétanos ; rage en cas de trek ; prophylaxie antipaludique uniquement pour les zones forestières frontalières. La dengue est présente : utilisez un répulsif, surtout en saison des pluies. Buvez de l'eau en bouteille ou filtrée."},
{id:"borders",t:"Postes-frontières",kh:"ព្រំដែន",link:["Bus, bateaux, trains","transports/"],b:"Thaïlande : Poipet / Aranyaprathet (le plus fréquenté, attention aux arnaques), Cham Yeam / Hat Lek (Koh Kong-Trat), Choam / Chong Sa-ngam (Anlong Veng-Surin), Prom / Ban Pakard (Pailin-Chanthaburi). Vietnam : Bavet / Moc Bai (vers Hô Chi Minh-Ville), Kaam Samnor / Vinh Xuong (bateau sur le Mékong vers Chau Doc), Prek Chak / Ha Tien (Kep-Phu Quoc), O'Yadav / Le Thanh (Ratanakiri-Pleiku). Laos : Trapeang Kriel / Nong Nok Khiene (Stung Treng-4 000 Îles). L'e-visa n'est accepté qu'à certains postes : vérifiez la liste."},
{id:"responsible",t:"Tourisme responsable",kh:"ទេសចរណ៍ទទួលខុសត្រូវ",b:"Ne montez pas sur les éléphants ; choisissez des sanctuaires qui les laissent libres (Elephant Valley Project, Mondulkiri Project). Ne visitez pas les orphelinats. Achetez auprès d'entreprises sociales (Artisans Angkor, Phare, Friends). Privilégiez l'écotourisme communautaire (Chi Phat, Chambok, Banteay Chhmar). Remplissez vos gourdes (carte Refill Cambodia). Habillez-vous avec respect dans les temples. Ne donnez pas d'argent aux enfants qui mendient : soutenez plutôt leurs écoles."},
{id:"plugs",t:"Prises, heure, essentiels",kh:"ផ្សេងៗ",b:"Électricité 230 V, prises de type A, C et G (un adaptateur universel couvre tout). Fuseau horaire UTC+7, pas de changement d'heure. Les commerces ouvrent de 7 h à 20 h. Les administrations ferment de 11 h 30 à 14 h. Jours fériés : Nouvel An khmer du 13 au 16 avril, Pchum Ben (septembre / octobre), Fête de l'eau (novembre), anniversaires royaux. L'alcool se vend partout ; fumer est interdit en intérieur en théorie."},
{id:"cost",t:"Budget",kh:"ថវិកា",link:["Budget voyage Cambodge","budget-voyage-cambodge/"],b:"Routard : 25 à 35 USD par jour (dortoir 5 à 10 USD, repas de rue 1,50 à 3 USD, bus 8 à 15 USD). Milieu de gamme : 60 à 120 USD (hôtel de charme 35 à 80 USD, repas au restaurant 6 à 15 USD, chauffeur privé partagé). Luxe : à partir de 250 USD. Pass Angkor : 37 USD pour 1 jour, 62 USD pour 3 jours, 72 USD pour 7 jours. La plupart des sites en province coûtent de 2 à 10 USD."},
{id:"events",t:"Calendrier des événements",kh:"ព្រឹត្តិការណ៍",link:["Événements et fêtes","evenements/"],b:"Angkor Sankranta / Nouvel An khmer (13 au 16 avril, à Siem Reap et partout), Fête royale des Semailles (mai), fête des ancêtres Pchum Ben (sept. / oct., les familles retournent au village), Bon Om Touk, la Fête de l'eau avec courses de pirogues sur le Tonlé Sap à Phnom Penh (pleine lune de novembre), semi-marathon international d'Angkor Wat (décembre), festival de lecture et d'écriture de Kampot (novembre), Festival de la mer (décembre, province côtière tournante), Festival du film du Cambodge (Phnom Penh)."}
];

/* ===== Pages détaillées déjà existantes, reliées depuis les fiches provinces ===== */
const GUIDES = {
 "siem-reap":[["Guide de Siem Reap","siem-reap/"],["Angkor Wat","angkor-wat/"],["Le parc d'Angkor","angkor/"]],
 "phnom-penh":[["Guide de Phnom Penh","phnom-penh/"],["Guide des quartiers","quartiers/"]],
 "kampot":[["Guide de Kampot","kampot/"]],
 "kep":[["Guide de Kep","kep/"]],
 "sihanoukville":[["Guide de Sihanoukville","sihanoukville/"],["Koh Rong","koh-rong/"],["Koh Rong Sanloem","koh-rong-sanloem/"]],
 "battambang":[["Guide de Battambang","battambang/"]],
 "mondulkiri":[["Guide du Mondulkiri","mondulkiri/"]],
 "pursat":[["Guide de Pursat","pursat/"]],
 "banteay-meanchey":[["Poipet","poipet/"]]
};
